version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8080 --workers 4 --log-level info --chdir /app/comments_classifier classifier.wsgi:application
    expose:
      - "8080"
    volumes:
      - static_volume:/app/staticfiles
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${VIRTUAL_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - app
    networks:
      - nginx-proxy
      - default

volumes:
  static_volume:

networks:
    nginx-proxy:
        external:
            name: net-nginx-proxy
