# Generated by Django 5.2.7 on 2025-10-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_toxic', models.BooleanField(verbose_name='Токсичный?')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='Доверенные данные')),
            ],
        ),
    ]
